---
# 'Calculation Service Generator' Service description
#
# for all 'key: value' pairs: no spaces, no capitals (snake_case)
# all values can (should) be changed by the user
# key names can be changed as well, except when indicated as 'IMMUTABLE'
#
# 'variables' sections (calculations input/output data) consist of 1 or more items: 'variable_name: variable_type'
# supported variable types are:  'int', 'float', 'str', 'bool', 'dict',
#                                'List[int]', 'List[str]', 'List[bool]', 'List[float]', 'List[List[float]]'
#
# The 'calculations' input data names ('receives') may contain duplicates (multiple calculation can use the same data)
# The 'calculations' output data names ('sends') should not contain duplicates
# When data is sent from one service to another, it is important the data name and structure
#   (list of 'variable_name: variable_type') are the same

default_context: # 'default_context'-key IMMUTABLE
    service_name: service_name # 'service_name'-key IMMUTABLE
    version: 1.0.0 # 'version'-key IMMUTABLE
    calculations: # 'calculations'-key IMMUTABLE
        calc1:
            receives: # 'receives'-key IMMUTABLE
                origin_service1:
                    input_data1:
                        input1_var1: bool
                        input1_var2: List[List[float]]
                    input_data2:
                        input2_var1: dict
                        input2_var2: List[float]
                        input2_var3: float
            sends: # 'sends'-key IMMUTABLE
                output_data1:
                    output1_var1: float
        calc2:
            receives: # 'receives'-key IMMUTABLE
                origin_service1:
                    input_data1:
                        input1_var1: bool
                        input1_var2: List[List[float]]
                origin_service2:
                    input_data3:
                        input3_var1: float
            sends: # 'sends'-key IMMUTABLE
                output_data2:
                    output2_var1: List[str]
                    output2_var2: float
                output_data3:
                    output3_var1: dict
