---
# 'DOTS service-generator' Service description
#
# for all 'key: value' pairs: no spaces, no capitals (snake_case)
# most values can be (should be) changed by the user as if indicated as 'IMMUTABLE'
# some key names can be changed as well except when not indicated as 'IMMUTABLE'
#
# 'variables' sections (service_config, new_step_data, calculations input/output data)
#     consist of 0 or more items: 'variable_name: variable_type'
# supported variable types are:  'int', 'float', 'str', 'bool', 'dict',
#                                'List[int]', 'List[float]', 'List[str]', 'List[bool]'
#
# The 'new_step_data' variables should be same for all services
# The 'calculations' output data names ('sends') should not contain duplicates
# The 'calculations' input names ('receives') may contain duplicates,
#     but the origin_service_name and variables have to be the same

default_context: # 'default_context'-key IMMUTABLE
    service_name: service_name # 'service_name'-key IMMUTABLE
    version: 1.0.0 # 'version'-key IMMUTABLE
    service_config: # 'service_config'-key IMMUTABLE
        config_data_dict: dict # 'config_data_dict'-key and 'dict'-type IMMUTABLE
        connected_input_models: dict # 'connected_input_models'-key and 'dict'-type IMMUTABLE (will be filled from ESDL file)
    new_step_data: # 'new_step_data'-key IMMUTABLE
        new_step_data_dict: dict # 'new_step_data_dict'-key and 'dict'-type IMMUTABLE
    calculations: # 'calculations'-key IMMUTABLE
        calc1:
            receives: # 'receives'-key IMMUTABLE
                origin_service1:
                    input_data1:
                        input1_var1: bool
                        input1_var2: List[float]
                    input_data2:
                        input2_var1: dict
                        input2_var2: bool
                        input2_var3: float
            sends: # 'sends'-key IMMUTABLE
                output_data1:
                    output1_var1: float
        calc2:
            receives: # 'receives'-key IMMUTABLE
                origin_service1:
                    input_data1:
                        input1_var1: bool
                        input1_var2: float
                origin_service2:
                    input_data3:
                        input3_var1: float
            sends: # 'sends'-key IMMUTABLE
                output_data2:
                    output2_var1: List[str]
                    output2_var2: float
                output_data3:
                    output3_var1: dict
